services:
  db:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - ./docker/mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: blogdb
      MYSQL_USER: username
      MYSQL_PASSWORD: password
  app:
    build: .
    image: blog
    container_name: api
    ports:
      - "8080:8080"
    env_file:
        - ".env"
