services:
  db:
    image: postgres:15
    container_name: postgres
    volumes:
      - ./database/init_db:/docker-entrypoint-initdb.d
      - ./database/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:  
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8